### ISSUE TITLE
Can't open.

### ISSUE THREAD

**Issue by ItzzCode** [bangyen/esolangs#2]
The program for me will open for a split second, before then closing.
I'm on Windows 10.

**Comment by bangyen** [comment]
What file are you trying to open?

**Comment by ItzzCode** [comment]
I tried to open Dig and DSDLAI.

**Comment by bangyen** [comment]
Did you set the first command line argument equal to the file you wish to interpret? The command should look like the following:
`python dig.py my_file.txt`

**Comment by ItzzCode** [comment]
That could help, ima try it.

**Comment by ItzzCode** [comment]
I have severely confused myself, need help.

**Comment by bangyen** [comment]
Here are the steps for using the interpreter:
1. Create a `.txt` file
2. Paste in the code to be interpreted
3. Move the `.txt` file to the same directory as `dig.py`
4. Open Windows PowerShell
5. Change the working directory to the one containing `dig.py` using the `cd`command
6. Type the command `python dig.py my_file.txt`, where `my_file.txt` is replaced with your text file

You need to also make sure that you have Python installed.
